services:
  postgres:
    image: "postgres:14-alpine"
    ports:
      - "5444:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
      POSTGRES_DB: ${POSTGRES_DB:-nutripanda}


#  api:
#    build:
#      context: .
#      dockerfile: Dockerfile

volumes:
  postgres-data:
